# Generated by Django 6.0.3 on 2026-03-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('source', models.CharField(choices=[('boticario', 'Boticário')], db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('target', models.CharField(blank=True, choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('unissex', 'Unissex')], db_index=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('perfume', 'Perfume'), ('colonia', 'Colônia'), ('body splash', 'Body Splash'), ('desodorante', 'Desodorante')], db_index=True, max_length=50, null=True)),
                ('flavor', models.CharField(blank=True, db_index=True, help_text='Família olfativa ou perfil aromático', max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review_count', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('image', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['source', 'external_id'], name='products_pr_source_3d1da8_idx'), models.Index(fields=['name', 'brand'], name='products_pr_name_13ef6e_idx'), models.Index(fields=['is_active', 'source'], name='products_pr_is_acti_1c4eb7_idx')],
                'unique_together': {('external_id', 'source')},
            },
        ),
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_user_id', models.CharField(db_index=True, max_length=30)),
                ('product_reference_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['whatsapp_user_id', '-created_at'], name='products_us_whatsap_87b467_idx')],
            },
        ),
    ]
